services:
  app_dev:
    image: anchor-python-bp-dev:latest
    command: ["sh", "-c", "alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 7001 --reload"]
    container_name: app_dev
    networks:
      - hng-network
    restart: unless-stopped
    ports:
      - 7006:7001
    working_dir: /app 
    volumes:
      - .env:/app/.env    
    depends_on:
      - dev_db

  dev_db:
    image: postgres:14.12
    container_name: dev_db
    restart: always
    volumes:
      - dev_db:/var/lib/postgresql/data
      - .env:/app/.env
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD?Variable not set}
      - POSTGRES_USER=${DB_USER?Variable not set}
      - POSTGRES_DB=${DB_NAME?Variable not set}
    networks:
      - hng-network

volumes:
  dev_db:

networks:
  hng-network:
    driver: bridge