"""Ensure id and foreign keys are of type String

Revision ID: 007a42e43be4
Revises: d97cd1f6afa7
Create Date: 2024-08-07 20:33:23.833030

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '007a42e43be4'
down_revision: Union[str, None] = 'd97cd1f6afa7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('is_builtin', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('roles', 'is_builtin')
    # ### end Alembic commands ###
