"""update non nullable orgid field to nullable in contact table

Revision ID: 0b4754ddf183
Revises: 7eaf47fca204
Create Date: 2024-08-16 16:19:14.822260

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b4754ddf183'
down_revision: Union[str, None] = '7eaf47fca204'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('contact_us', 'org_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('contact_us', 'org_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
