"""fix: added is_owner to org_user_role table

Revision ID: 0c0978bc2925
Revises: 493877a22513
Create Date: 2024-08-10 04:26:02.132975

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c0978bc2925'
down_revision: Union[str, None] = '493877a22513'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_organisation_roles', sa.Column('is_owner', sa.Boolean(), server_default='false', nullable=True))
    op.drop_column('user_organisation_roles', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_organisation_roles', sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.drop_column('user_organisation_roles', 'is_owner')
    # ### end Alembic commands ###
