"""add data privacy settings and team members tables

Revision ID: 1778dd5dc8a6
Revises: 3cfce484758c
Create Date: 2024-08-06 01:11:37.170473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1778dd5dc8a6'
down_revision: Union[str, None] = '3cfce484758c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_privacy_settings',
    sa.Column('profile_visibility', sa.Boolean(), server_default='true', nullable=True),
    sa.Column('share_data_with_partners', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('receice_email_updates', sa.Boolean(), server_default='true', nullable=True),
    sa.Column('enable_two_factor_authentication', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('use_data_encryption', sa.Boolean(), server_default='true', nullable=True),
    sa.Column('allow_analytics', sa.Boolean(), server_default='true', nullable=True),
    sa.Column('personalized_ads', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_privacy_settings_id'), 'data_privacy_settings', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_data_privacy_settings_id'), table_name='data_privacy_settings')
    op.drop_table('data_privacy_settings')
    # ### end Alembic commands ###