"""updated billing model ensuing that plan name is unique

Revision ID: 1db8122b91b7
Revises: 2c831357263d
Create Date: 2024-08-11 13:50:40.466628

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1db8122b91b7'
down_revision: Union[str, None] = '2c831357263d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
