"""Ensure id and foreign keys are of type String

Revision ID: 1fc08cda8f3b
Revises: a8eeee3dda1c
Create Date: 2024-08-07 21:56:40.794371

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1fc08cda8f3b'
down_revision: Union[str, None] = 'a8eeee3dda1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_organization_roles', sa.Column('role_id', sa.String(), nullable=True))
    op.drop_constraint('user_organization_roles_role_name_fkey', 'user_organization_roles', type_='foreignkey')
    op.create_foreign_key(None, 'user_organization_roles', 'roles', ['role_id'], ['id'], ondelete='CASCADE')
    op.drop_column('user_organization_roles', 'role_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_organization_roles', sa.Column('role_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'user_organization_roles', type_='foreignkey')
    op.create_foreign_key('user_organization_roles_role_name_fkey', 'user_organization_roles', 'roles', ['role_name'], ['name'], ondelete='CASCADE')
    op.drop_column('user_organization_roles', 'role_id')
    # ### end Alembic commands ###
