"""initial migration

Revision ID: 2a8bed88c439
Revises: a4d7853646c4
Create Date: 2024-07-24 13:55:09.843379

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a8bed88c439'
down_revision: Union[str, None] = 'a4d7853646c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('tags', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'tags')
    # ### end Alembic commands ###
