"""added models to support billing subscription

Revision ID: 2e1bdb317917
Revises: 95a09b7f5c2c
Create Date: 2024-08-10 18:53:02.873361

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e1bdb317917'
down_revision: Union[str, None] = '95a09b7f5c2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
