"""fix: resolved naming issues

Revision ID: 3b6d16e973a2
Revises: 5e8d48445236
Create Date: 2024-08-07 17:34:13.208213

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b6d16e973a2'
down_revision: Union[str, None] = '5e8d48445236'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('name', sa.String(), nullable=False))
    op.add_column('organizations', sa.Column('email', sa.String(), nullable=True))
    op.add_column('organizations', sa.Column('type', sa.String(), nullable=True))
    op.add_column('organizations', sa.Column('description', sa.String(), nullable=True))
    op.drop_constraint('organizations_company_email_key', 'organizations', type_='unique')
    op.drop_constraint('organizations_company_name_key', 'organizations', type_='unique')
    op.create_unique_constraint(None, 'organizations', ['email'])
    op.create_unique_constraint(None, 'organizations', ['name'])
    op.drop_column('organizations', 'company_name')
    op.drop_column('organizations', 'organization_type')
    op.drop_column('organizations', 'lga')
    op.drop_column('organizations', 'company_email')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('company_email', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('organizations', sa.Column('lga', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('organizations', sa.Column('organization_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('organizations', sa.Column('company_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'organizations', type_='unique')
    op.drop_constraint(None, 'organizations', type_='unique')
    op.create_unique_constraint('organizations_company_name_key', 'organizations', ['company_name'])
    op.create_unique_constraint('organizations_company_email_key', 'organizations', ['company_email'])
    op.drop_column('organizations', 'description')
    op.drop_column('organizations', 'type')
    op.drop_column('organizations', 'email')
    op.drop_column('organizations', 'name')
    # ### end Alembic commands ###
