"""Ensure id and foreign keys are of type String

Revision ID: 44f7da26ee88
Revises: b27028b0327e
Create Date: 2024-08-08 18:21:40.759920

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44f7da26ee88'
down_revision: Union[str, None] = 'b27028b0327e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###