"""updated billing model ensuing that plan name is unique

Revision ID: 4b2076898c06
Revises: 1db8122b91b7
Create Date: 2024-08-11 13:58:07.075700

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b2076898c06'
down_revision: Union[str, None] = '1db8122b91b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
