"""Initial migration

Revision ID: 5e7eeb0421b3
Revises: a09b0a4fbd24
Create Date: 2024-07-21 20:34:11.459725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e7eeb0421b3'
down_revision: Union[str, None] = 'a09b0a4fbd24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('organizations_name_key', 'organizations', type_='unique')
    op.drop_index('ix_permissions_name', table_name='permissions')
    op.create_index(op.f('ix_permissions_name'), 'permissions', ['name'], unique=False)
    op.drop_index('ix_roles_role_name', table_name='roles')
    op.create_index(op.f('ix_roles_role_name'), 'roles', ['role_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_roles_role_name'), table_name='roles')
    op.create_index('ix_roles_role_name', 'roles', ['role_name'], unique=True)
    op.drop_index(op.f('ix_permissions_name'), table_name='permissions')
    op.create_index('ix_permissions_name', 'permissions', ['name'], unique=True)
    op.create_unique_constraint('organizations_name_key', 'organizations', ['name'])
    # ### end Alembic commands ###
