"""update oauth table to make access and refresh token nullable

Revision ID: 6d9c88b1af24
Revises: 3b6d16e973a2
Create Date: 2024-08-08 00:21:55.171541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d9c88b1af24'
down_revision: Union[str, None] = '3b6d16e973a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_comments',
    sa.Column('product_id', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_comments_id'), 'product_comments', ['id'], unique=False)
    op.alter_column('oauth', 'access_token',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('oauth', 'refresh_token',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('oauth', 'refresh_token',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('oauth', 'access_token',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index(op.f('ix_product_comments_id'), table_name='product_comments')
    op.drop_table('product_comments')
    # ### end Alembic commands ###
