"""added reset_password_token, reset_password_token.user_id and user.reset_password_token

Revision ID: 7eaf47fca204
Revises: b99c97c70536
Create Date: 2024-08-13 20:23:50.881760

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7eaf47fca204'
down_revision: Union[str, None] = 'b99c97c70536'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
