"""Refactor uuid to string

Revision ID: 83e7c9c9fb9f
Revises: 3523564e7706
Create Date: 2024-07-24 22:34:16.858871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83e7c9c9fb9f'
down_revision: Union[str, None] = '3523564e7706'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
