"""update contact-us model with org_id

Revision ID: 899536f0532b
Revises: 5f8e13d19ccb
Create Date: 2024-07-31 08:28:12.648638

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '899536f0532b'
down_revision: Union[str, None] = '5f8e13d19ccb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contact_us', sa.Column('phone_number', sa.String(), nullable=False))
    op.add_column('contact_us', sa.Column('org_id', sa.String(), nullable=False))
    op.create_foreign_key(None, 'contact_us', 'organizations', ['org_id'], ['id'])
    op.drop_column('contact_us', 'title')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contact_us', sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'contact_us', type_='foreignkey')
    op.drop_column('contact_us', 'org_id')
    op.drop_column('contact_us', 'phone_number')
    # ### end Alembic commands ###
