"""Ensure id and foreign keys are of type String

Revision ID: 8caa1a06240c
Revises: ac6ee5ebdd31
Create Date: 2024-08-08 02:02:59.171077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8caa1a06240c'
down_revision: Union[str, None] = 'ac6ee5ebdd31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###