"""remove desctiption

Revision ID: 8d7d0a37a9d8
Revises: 83e7c9c9fb9f
Create Date: 2024-07-24 22:40:14.373494

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d7d0a37a9d8'
down_revision: Union[str, None] = '83e7c9c9fb9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
