"""added models to support billing subscription

Revision ID: 95a09b7f5c2c
Revises: 5048f25d8274
Create Date: 2024-08-10 18:47:09.891441

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95a09b7f5c2c'
down_revision: Union[str, None] = '5048f25d8274'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
