"""add data privacy model

Revision ID: 983b8cd3f2fa
Revises: aeb162769644
Create Date: 2024-08-06 09:52:44.160060

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '983b8cd3f2fa'
down_revision: Union[str, None] = 'aeb162769644'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_privacy',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('profile_visibility', sa.Boolean(), nullable=False),
    sa.Column('share_data_with_partners', sa.Boolean(), nullable=False),
    sa.Column('receive_email_updates', sa.Boolean(), nullable=False),
    sa.Column('enable_2fa', sa.Boolean(), nullable=False),
    sa.Column('use_data_encryption', sa.Boolean(), nullable=False),
    sa.Column('allow_analytics', sa.Boolean(), nullable=False),
    sa.Column('show_personalized_ads', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_privacy_id'), 'data_privacy', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_data_privacy_id'), table_name='data_privacy')
    op.drop_table('data_privacy')
    # ### end Alembic commands ###
