"""blog categories

Revision ID: 9eb774b0787b
Revises: 534047ee3520
Create Date: 2024-07-21 23:03:42.987383

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9eb774b0787b'
down_revision: Union[str, None] = '534047ee3520'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blog_categories',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_blog_categories_id'), 'blog_categories', ['id'], unique=False)
    op.drop_table('newsletters')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('newsletters',
    sa.Column('id', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='newsletters_pkey'),
    sa.UniqueConstraint('email', name='newsletters_email_key')
    )
    op.drop_index(op.f('ix_blog_categories_id'), table_name='blog_categories')
    op.drop_table('blog_categories')
    # ### end Alembic commands ###
