"""merged heads

Revision ID: 9ebd43784f48
Revises: d7a2a1640591
Create Date: 2024-08-08 03:39:48.825919

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ebd43784f48'
down_revision: Union[str, None] = 'd7a2a1640591'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('oauth', 'access_token',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('oauth', 'refresh_token',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('product_comments', 'user_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint('product_comments_user_id_fkey', 'product_comments', type_='foreignkey')
    op.create_foreign_key(None, 'product_comments', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.add_column('roles', sa.Column('is_builtin', sa.Boolean(), nullable=True))
    op.alter_column('user_organization_roles', 'role_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_organization_roles', 'role_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('roles', 'is_builtin')
    op.drop_constraint(None, 'product_comments', type_='foreignkey')
    op.create_foreign_key('product_comments_user_id_fkey', 'product_comments', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('product_comments', 'user_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('oauth', 'refresh_token',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('oauth', 'access_token',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
