"""Ensure id and foreign keys are of type String

Revision ID: a8eeee3dda1c
Revises: 007a42e43be4
Create Date: 2024-08-07 21:37:59.222921

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8eeee3dda1c'
down_revision: Union[str, None] = '007a42e43be4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_organisation_roles', sa.Column('role_name', sa.String(), nullable=False))
    op.drop_constraint('user_organisation_roles_role_id_fkey', 'user_organisation_roles', type_='foreignkey')
    op.create_foreign_key(None, 'user_organisation_roles', 'roles', ['role_name'], ['name'], ondelete='CASCADE')
    op.drop_column('user_organisation_roles', 'role_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_organisation_roles', sa.Column('role_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'user_organisation_roles', type_='foreignkey')
    op.create_foreign_key('user_organisation_roles_role_id_fkey', 'user_organisation_roles', 'roles', ['role_id'], ['id'], ondelete='CASCADE')
    op.drop_column('user_organisation_roles', 'role_name')
    # ### end Alembic commands ###
