"""newsubs

Revision ID: af8459ffc616
Revises: e63f024c23eb
Create Date: 2024-08-11 17:43:47.369492

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af8459ffc616'
down_revision: Union[str, None] = 'e63f024c23eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('newsletter_subscribers', 'newsletter_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint('organisations_name_key', 'organisations', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('organisations_name_key', 'organisations', ['name'])
    op.alter_column('newsletter_subscribers', 'newsletter_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
