"""Ensure id and foreign keys are of type String

Revision ID: b27028b0327e
Revises: 8caa1a06240c
Create Date: 2024-08-08 17:49:49.925575

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b27028b0327e'
down_revision: Union[str, None] = '8caa1a06240c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('permissions', sa.Column('title', sa.String(), nullable=False))
    op.drop_constraint('permissions_name_key', 'permissions', type_='unique')
    op.create_unique_constraint(None, 'permissions', ['title'])
    op.drop_column('permissions', 'name')
    op.add_column('roles', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('roles', 'description')
    op.add_column('permissions', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'permissions', type_='unique')
    op.create_unique_constraint('permissions_name_key', 'permissions', ['name'])
    op.drop_column('permissions', 'title')
    # ### end Alembic commands ###