"""created a new db after I messed with my migration

Revision ID: b74e51d32a12
Revises: 05faae41758c
Create Date: 2024-07-25 16:49:42.418417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b74e51d32a12'
down_revision: Union[str, None] = '05faae41758c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('newsletters', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('newsletters', 'content',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('newsletters', 'content',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('newsletters', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
