"""updated billing model ensuing that plan name is unique

Revision ID: b7e8db61eb86
Revises: 2e1bdb317917
Create Date: 2024-08-11 09:55:41.558757

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7e8db61eb86'
down_revision: Union[str, None] = '2e1bdb317917'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'billing_plans', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'billing_plans', type_='unique')
    # ### end Alembic commands ###
