"""added is_deleted and is_super_admin fiedl to user model

Revision ID: ba1f307177c1
Revises: 534047ee3520
Create Date: 2024-07-21 18:40:17.941403

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba1f307177c1'
down_revision: Union[str, None] = '534047ee3520'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('id_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=True))
    op.add_column('users', sa.Column('is_super_admin', sa.Boolean(), server_default=sa.text('false'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_super_admin')
    op.drop_column('users', 'id_deleted')
    # ### end Alembic commands ###
