"""billing plan model modification

Revision ID: bf7d62baa76f
Revises: 87280d61ce24
Create Date: 2024-07-29 11:47:33.184493

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf7d62baa76f'
down_revision: Union[str, None] = '87280d61ce24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('billing_plans', sa.Column('duration', sa.String(), nullable=False))
    op.add_column('billing_plans', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('billing_plans', 'description')
    op.drop_column('billing_plans', 'duration')
    # ### end Alembic commands ###
