"""updated billing model ensuing that plan name is unique

Revision ID: c82575f5f4ed
Revises: 4b2076898c06
Create Date: 2024-08-11 16:04:22.651487

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c82575f5f4ed'
down_revision: Union[str, None] = '4b2076898c06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_organisation_roles', sa.Column('status', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_organisation_roles', 'status')
    # ### end Alembic commands ###
