"""updated billing model ensuing that plan name is unique

Revision ID: c8e8bd65628a
Revises: d75a3dc8e9bf
Create Date: 2024-08-11 13:01:10.616166

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8e8bd65628a'
down_revision: Union[str, None] = 'd75a3dc8e9bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
