"""updated billing model ensuing that plan name is unique

Revision ID: c9d13f346b57
Revises: b7e8db61eb86
Create Date: 2024-08-11 10:04:26.675695

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9d13f346b57'
down_revision: Union[str, None] = 'b7e8db61eb86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
