"""Generate migration to capture latest changes

Revision ID: cceffcebcee6
Revises: 519cd8ecce4b
Create Date: 2024-07-29 13:45:00.422557

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cceffcebcee6'
down_revision: Union[str, None] = '519cd8ecce4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
