"""updated billing model ensuing that plan name is unique

Revision ID: d75a3dc8e9bf
Revises: cb921ac1eb00
Create Date: 2024-08-11 12:44:03.085518

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd75a3dc8e9bf'
down_revision: Union[str, None] = 'cb921ac1eb00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('organisations_name_key', 'organisations', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('organisations_name_key', 'organisations', ['name'])
    # ### end Alembic commands ###
