openapi: 3.0.0

info:
  description: This API provides detail to our Saas boilerplate endpoints.
  version: "1.0.0"
  title: HNG stage-three backend task
  contact:
    email: dynamo@gmail.com
  license:
    name: Apache 2.0
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"

tags:
  - name: Guide
  - name: Authentication
    # description: Secured Admin-only calls
  - name: Organisation
    # description: Operations available to regular developers
  - name: Wishlist

paths:
  /guide:
    get:
      tags:
        - Guide
      summary: searches inventory
      operationId: searchInventory
      description: |
        By passing in the appropriate options, you can search for
        available inventory in the system
      parameters:
        - in: query
          name: searchString
          description: pass an optional search string for looking up inventory
          required: false
          schema:
            type: string
        - in: query
          name: skip
          description: number of records to skip for pagination
          schema:
            type: integer
            format: int32
            minimum: 0
        - in: query
          name: limit
          description: maximum number of records to return
          schema:
            type: integer
            format: int32
            minimum: 0
            maximum: 50
      responses:
        "200":
          description: search results matching criteria
          content:
            application/json:
              schema:
                type: array
                # items:
                #   $ref: "#/components/schemas/InventoryItem"
        "400":
          description: bad input parameter
    post:
      tags:
        - Guide
      summary: adds an inventory item
      operationId: addInventory
      description: Adds an item to the system
      responses:
        "201":
          description: item created
        "400":
          description: "invalid input, object invalid"
        "409":
          description: an existing item already exists
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/InventoryItem"
        description: Inventory item to add

  # forgot-password
  /api/v1/forgot-password:
    post:
      tags:
        - Authentication
      summary: Send email to reset user's password
      operationId: forgotPassword
      description: |
        Sends an email to the user with a link to reset their password
      responses:
        "200":
          description: forgot password success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Success"
        "400":
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ValidationError"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ForgotPassword"

  # reset-password
  /api/v1/change-password:
    post:
      tags:
        - Authentication
      summary: Change a user's password
      operationId: changePassword
      description: |
        Change a user's password
      responses:
        "200":
          description: Password changed successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Success"
        "400":
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ValidationError"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ChangePassword"

components:
  schemas:
    Success:
      type: object
      required:
        - status
        - message
        - data
      properties:
        status:
          type: string
          format: int32
          example: "success"
        message:
          type: string
          format: int64
          example: "request processed successfully"
        data:
          type: object

    Error:
      type: object
      required:
        - status
        - message
        - statusCode
      properties:
        status:
          type: string
          format: int32
        message:
          type: string
          format: int64
        statusCode:
          type: number

    ValidationError:
      type: object
      required:
        - errors
      properties:
        errors:
          type: array
          items:
            type: object
            required:
              - field
              - message
            properties:
              field:
                type: string
                format: int32
              message:
                type: string
                format: int64

    ForgotPassword:
      type: object
      required:
        - email
      properties:
        email:
          type: string
          format: int32
          example: example@mail.com

    ChangePassword:
      type: object
      required:
        - old_password
        - new_password
      properties:
        old_password:
          type: string
          format: password
          example: "@password123"
        new_password:
          type: string
          format: password
          example: "@password123"

    # Guidelines for a quicker schema design

    InventoryItem:
      type: object
      required:
        - id
        - name
        - manufacturer
        - releaseDate
      properties:
        id:
          type: string
          format: uuid
          example: d290f1ee-6c54-4b01-90e6-d701748f0851
        name:
          type: string
          example: Widget Adapter
        releaseDate:
          type: string
          format: date-time
          example: "2016-08-29T09:12:33.001Z"
        manufacturer:
          $ref: "#/components/schemas/Manufacturer"
    Manufacturer:
      required:
        - name
      properties:
        name:
          type: string
          example: ACME Corporation
        homePage:
          type: string
          format: url
          example: "https://www.acme-corp.com"
        phone:
          type: string
          example: 408-867-5309
      type: object
