EMAIL_IN_USE = "This email is already in use."
NOT_FOUND = "Not found!"
ID_OR_UNIQUE_ID_REQUIRED = "ID or Unique ID required!"
INVALID_CREDENTIALS = "Invalid Credentials!"
COULD_NOT_VALIDATE_CRED = "Could not validate credentials."
SUCCESS = "SUCCESS"
EXPIRED="Token expired."
