name: CD

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
          virtual-environment: venv

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Copy .env.prod
        run: cp .env.prod .env

      - name: Run migrations
        run: |
          alembic upgrade head

      - name: Deploy application
        run: |
          ssh user@your-server "cd /path/to/app && git pull origin main"
        run: |
          ssh user@your-server "source venv/bin/activate && pip install -r requirements.txt"
        run: |
          ssh user@your-server "alembic upgrade head && systemctl restart your-app"